#[cfg_attr(
    feature = "serde-support",
    derive(serde::Deserialize, serde::Serialize)
)]
#[cfg_attr(feature = "serde-support", serde(rename_all = "snake_case"))]
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum AuditLogChangeKey {
    AfkChannelId,
    AfkTimeout,
    Allow,
    ApplicationId,
    AvatarHash,
    Bitrate,
    ChannelId,
    Code,
    Color,
    Deaf,
    DefaultMessageNotifications,
    Deny,
    ExplicitContentFilter,
    Hoist,
    IconHash,
    Id,
    InviterId,
    MaxAge,
    MaxUses,
    Mentionable,
    MfaLevel,
    Mute,
    Name,
    Nick,
    Nsfw,
    OwnerId,
    PermissionOverwrites,
    Permissions,
    Position,
    PruneDeleteDays,
    #[cfg_attr(feature = "serde-support", serde(rename = "$add"))]
    RoleAdded,
    #[cfg_attr(feature = "serde-support", serde(rename = "$remove"))]
    RoleRemoved,
    Region,
    SplashHash,
    Temporary,
    Topic,
    Type,
    Uses,
    VanityUrlCode,
    VerificationLevel,
    WidgetChannelId,
    WidgetEnabled,
}
