name: Check documentation

on: [push, pull_request]

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/debug
          key: ${{ runner.os }}-docs-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build docs
        env:
          RUSTDOCFLAGS: --cfg docsrs -D broken_intra_doc_links
        run: |
          cargo doc --workspace --no-deps
          cargo doc -p twilight-util --no-deps --all-features

  sync-readme:
    name: Sync readme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install cargo-sync-readme
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-sync-readme
          version: latest

      - name: Run in command-parser
        run: cd command-parser && cargo sync-readme --check
      - name: Run in gateway
        run: cd gateway && cargo sync-readme --check
      - name: Run in http
        run: cd http && cargo sync-readme --check
      - name: Run in lavalink
        run: cd lavalink && cargo sync-readme --check
      - name: Run in model
        run: cd model && cargo sync-readme --check
      - name: Run in standby
        run: cd standby && cargo sync-readme --check
      - name: Run in twilight
        run: cd twilight && cargo sync-readme --check
      - name: Run in embed-builder
        run: cd embed-builder && cargo sync-readme --check
      - name: Run in mention
        run: cd mention && cargo sync-readme --check
      - name: Run in util
        run: cd util && cargo sync-readme --check
